name: .NET Framework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v1
    - name: Restore dependencies
      run: nuget restore YourSolution.sln
    - name: Build
      run: msbuild YourSolution.sln /p:Configuration=Release
    - name: Test
      run: |